### ISSUE TITLE
Toolkit crashes after a few seconds

### ISSUE THREAD

**Issue by swappel** [ArchLeaders/Breath-of-the-Wild-Basic-Mod-Creator#1]
Once i click on the .exe installer file, the window opens, but closes after a few seconds.
The windows is not clickable either.

In the video below, im not clicking on anything. Only at the beginning, when i click on the .exe file
https://user-images.githubusercontent.com/67843782/159897641-e0b41d25-9df7-4dac-b54a-42cff785a835.mp4

**Comment by ArchLeaders** [comment]
It seems to have been some odd internal error. It should be fixed in [0.7.3b](https://github.com/ArchLeaders/Botw-Modding-Toolkit/releases/tag/0.7.3b).

**Comment by ArchLeaders** [comment]
It wasn't fixed in [0.7.3b](https://github.com/ArchLeaders/Botw-Modding-Toolkit/releases/tag/0.7.3b).
Fixed in [v0.7.5b](https://github.com/ArchLeaders/Botw-Modding-Toolkit/releases/tag/0.7.5b)
